### ISSUE TITLE
v1.2.23 unable to load: Unable to import component: cannot import name 'ATTR_FORECAST_NATIVE_PRECIPITATION'

### ISSUE THREAD

**Issue by bcutter** [FL550/dwd_weather#60]
## Version of home_assistant
2022.6.7

## Version of the custom_component
1.2.23

## Describe the bug
After updating from v1.2.22 to v1.2.23 the integration does not load anymore.

## Debug log

```text

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 22:00:27 (1 occurrences)
Last logged: 22:00:27

Setup failed for custom integration dwd_weather: Unable to import component: cannot import name 'ATTR_FORECAST_NATIVE_PRECIPITATION' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)

```

**Comment by FL550** [comment]
Please update your HA instance. This attributes was added in a later version.

**Comment by FL550** [comment]
Thanks for the hint. I wasn't aware of this functionality. I updated the release 😃
